### ISSUE TITLE
Reimplement the debug screen

### ISSUE THREAD

**Issue by nsg** [konstructs/client#106]
The debug screen was lost in the rewrite in PR #103. Reimplement something similar again.

![screenshot from 2015-12-25 18 04 31](https://cloud.githubusercontent.com/assets/16388/12003878/ff045d80-ab31-11e5-8d6d-c98544b448a5.png)

Possible use NanoGUI for this? or do we like to use the much simpler and faster text functions?

**Comment by petterarvidsson** [comment]
First I thought that the debug screen is not performance critical and could as well be in nanogui, but then I realized that one of the most used features is the FPS counter... That is very performance critical, you can't have it drop just because you show it or it would be pretty useless. So maybe we should do it as before?

**Comment by nsg** [comment]
True, I agree. When we have text render ability back I think we just reimplement like before.

**Comment by petterarvidsson** [comment]
This was fixed by #222
