### ISSUE TITLE
Increase player height

### ISSUE THREAD

**Issue by nsg** [konstructs/client#134]
I think the player feels a little short, by the look of it the camera position looks to be about 1.3 or 1.4 blocks. It feels a little weird when moving up trough a mountain, I suggest that we increase it to somewhere between 1.6 -  1.8 blocks.

For reference, Steve in Minecraft is 1.7.

**Comment by Henningstone** [comment]
That was my first thought when playing the game for the first time.
> Holy, how big are those blocks?! Or am I that small??
:grinning: :+1:

**Comment by nsg** [comment]
Yeah, it has annoyed me for over a year but I got used to it and forgot about it :)

**Comment by petterarvidsson** [comment]
After some testing I recorded the following with a 0.5 blocks higher camera position and a FOV of 70 rather than 60 (it's the teaser video for the next release :smile: ):
https://www.youtube.com/watch?v=OBTYo2HzP8E

I think it's a clear improvement. The code is in konstructs/client#159. What do you think?

**Comment by nsg** [comment]
... and It's merged :)
